### ISSUE TITLE
error message format wrong?

### ISSUE THREAD

**Issue by w7lau** [robidev/iec61850_open_client#1]
File "/mnt/hgfs/ubuntumnt/py61850_client/libiec61850client.py", line 221, in discovery
    logger.error("could not get logical device list, error:%i" % error)
TypeError: %i format: a number is required, not c_int

maybe we need use error.value?

**Comment by robidev** [comment]
Correct, will fix it asap. Thnx!

Op za 11 jul. 2020 11:11 schreef w7lau <notifications@github.com>:

**Comment by robidev** [comment]
issue has been fixed. error.value has been added.
